easy_admin:
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    design:
        menu:
            - ExpenseEvent
            - Event
            - Period
            - User
            - { label: 'Back to app', route: 'event_list' }
    entities:
        # List the entity class name you want to manage
        Event:
            class: App\Entity\Event
            list:
                fields:
                    - date
                    - type
                    - addressLabel
                    - closed
                    - period
            form:  # <-- 'form' is applied to both 'new' and 'edit' views
                fields:
                    - date
                    - type
                    - addressLabel
                    - address
                    - postalCode
                    - city
                    - closed
                    - period
        ExpenseEvent:
            class: App\Entity\ExpenseEvent
            list:
                fields:
                    - id
                    - user.username
                    - { property: "event.date", type: "date"}
        User:
            class: App\Entity\User
        Period:
            class: App\Entity\Period
    user:
        name_property_path: 'username'
