version: '3'
services:
  db:
    image: mysql:5.7
    container_name: gestionfrais_db
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: gestionfrais
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
  web:
    image: "gestionfrais:latest"
    container_name: gestionfrais_web
    ports:
      - "8000:8000"
    volumes:
      - .:/srv/app
    links:
      - db
    depends_on:
      - db
    command: ["./docker/wait-for-it.sh", "db:3306", "--", "sh", "/srv/init.sh"]
