version: '3'
services:
  db:
    image: mysql:5.7
    container_name: gestionfrais_db
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: gestionfrais
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
  web:
    image: nginx:latest
    container_name: gestionfrais_web
    ports:
        - "8000:80"
    volumes:
        - .:/srv/app
        - ./docker/site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
    depends_on:
      - php
  php:
    image: "gestionfraisphp:latest"
    container_name: gestionfrais_php
    volumes:
      - .:/srv/app
    links:
      - db
    depends_on:
      - db
    entrypoint: /srv/app/docker/wait-for-it.sh db:3306 -- sh /srv/app/docker/init.sh
