version: '3'
services:
  database:
    image: mysql:5.7
    container_name: gestionfrais_db
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: gestionfrais
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
  mailer:
    image: sj26/mailcatcher
    container_name: gestionfrais_mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
